### ISSUE TITLE
docker image and node version error

### ISSUE THREAD

**Issue by mounicakadapagunta** [mounicakadapagunta/errors#4]
[2023-09-05 03:59:18]  INFO executing the "npx -p @sap/cds-dk cds build --production" command...
2023-09-05T03:59:31.9223214Z info  mtaBuild - /home/mta/.npm/_npx/65/lib/node_modules/@sap/cds-dk/bin/cds.js:57
2023-09-05T03:59:31.9223753Z info  mtaBuild -       process.exitCode ??= 1
2023-09-05T03:59:31.9229078Z info  mtaBuild -                        ^^^
2023-09-05T03:59:31.9229269Z info  mtaBuild - 
2023-09-05T03:59:31.9232740Z info  mtaBuild - SyntaxError: Unexpected token '??='
2023-09-05T03:59:31.9234815Z info  mtaBuild -     at wrapSafe (internal/modules/cjs/loader.js:1001:16)
2023-09-05T03:59:31.9236931Z info  mtaBuild -     at Module._compile (internal/modules/cjs/loader.js:1049:27)
2023-09-05T03:59:31.9239032Z info  mtaBuild -     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
2023-09-05T03:59:31.9240903Z info  mtaBuild -     at Module.load (internal/modules/cjs/loader.js:950:32)
2023-09-05T03:59:31.9243102Z info  mtaBuild -     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
2023-09-05T03:59:31.9245197Z info  mtaBuild -     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
2023-09-05T03:59:31.9247065Z info  mtaBuild -     at internal/main/run_main_module.js:17:47
2023-09-05T03:59:32.5269672Z error mtaBuild - ..............[2023-09-05 03:59:32] ERROR the "before-all"" build failed: could not execute the "npx -p @sap/cds-dk cds build --production" command: exit status 1
2023-09-05T03:59:32.5278013Z info  mtaBuild - make: *** [Makefile_20230905035815.mta:28: pre_build] Error 1
2023-09-05T03:59:32.5287971Z info  mtaBuild - Error: could not build the MTA project: could not execute the "make -f Makefile_20230905035815.mta p=CF mtar=oms.mtar strict=true mode= t=\"/home/vsts/work/1/s\"" command: exit status 2
2023-09-05T03:59:32.5353996Z info  mtaBuild - fatal error: errorDetails{"category":"build","correlationId":"https://dev.azure.com/hyperspace-pipelines/TTC-BASIC-OMS/oms-develop/_build/results?buildId=2815617","error":"running command 'mbt' failed: cmd.Run() failed: exit status 1","library":"SAP/jenkins-library","message":"failed to execute mta build","result":"failure","stepName":"mtaBuild","time":"2023-09-05T03:59:32.53490388Z"}
2023-09-05T03:59:32.5361469Z fatal mtaBuild - failed to execute mta build - running command 'mbt' failed: cmd.Run() failed: exit status 1
2023-09-05T03:59:32.5362648Z info  mtaBuild - persisting reports to GCS is disabled, because gcsBucketId is empty

**Comment by mounicakadapagunta** [comment]
SOLUTION:

Have to maintain node version in the package.json 
maintain dicker image version in config.yml  dockerImage: 'devxci/mbtci-java17-node16:latest'
