### ISSUE TITLE
java.lang.IllegalStateException: Failed to upload report: Error 500 

### ISSUE THREAD

**Issue by mounicakadapagunta** [mounicakadapagunta/errors#6]
info  sonarExecuteScan -     <h2>The upstream is not available</h2>
info  sonarExecuteScan -   </body>
info  sonarExecuteScan - </html>
info  sonarExecuteScan - 	at org.sonarqube.ws.client.BaseResponse.failIfNotSuccessful(BaseResponse.java:36)
info  sonarExecuteScan - 	at org.sonar.scanner.bootstrap.DefaultScannerWsClient.failIfUnauthorized(DefaultScannerWsClient.java:126)
info  sonarExecuteScan - 	at org.sonar.scanner.bootstrap.DefaultScannerWsClient.call(DefaultScannerWsClient.java:89)
info  sonarExecuteScan - 	at org.sonar.scanner.report.ReportPublisher.upload(ReportPublisher.java:224)
info  sonarExecuteScan - 	... 21 more
error sonarExecuteScan - ERROR: 
error sonarExecuteScan - ERROR: Re-run SonarScanner using the -X switch to enable full debug logging.
info  sonarExecuteScan - fatal error: errorDetails{"category":"undefined","correlationId":"[https://dev.azure.com/hyperspace-pipelines/content-agent/content-agent-go-deployer/_build/results?buildId=2955357","error":"running](https://dev.azure.com/hyperspace-pipelines/content-agent/content-agent-go-deployer/_build/results?buildId=2955357%22,%22error%22:%22running) command 'sonar-scanner' failed: cmd.Run() failed: exit status 1","library":"SAP/jenkins-library","message":"Execution failed","result":"failure","stepName":"sonarExecuteScan","time":"2023-09-21T09:08:04.489579285Z"}
fatal sonarExecuteScan - Execution failed - running command 'sonar-scanner' failed: cmd.Run() failed: exit status 1

**Comment by mounicakadapagunta** [comment]
project is not created
